# Generated by Django 6.0 on 2025-12-27 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carroproduto',
            old_name='Produto',
            new_name='produto',
        ),
    ]
